name: assaman-suuf

include:
  - path: ./orchestration/docker-compose.yaml
    env_file: .env

  - path: ./ingestion/kafka_source/docker-compose.yml
    env_file: .env

  - path: ./ingestion/mongodb_source/docker-compose.yml
    env_file: .env

  - path: ./ml/docker-compose.yml
    env_file: .env

  - path: ./frontend/docker-compose.yaml
    env_file: .env

  - path: ./api/docker-compose.yml
    env_file: .env