name: dataflow360
version: '1.0.0'
config-version: 2

profile: dataflow360

model-paths: ["models"]

models:
  dataflow360:
    staging:
      +materialized: view

    intermediate:
      +schema: INTERMEDIATE
      +materialized: view

    marts:
      +schema: MARTS
      +materialized: table
