version: 2

models:

  # Données climatiques nettoyées.
  - name: stg_climat
    columns:
      - name: id
        tests:
          - not_null
          - unique

      - name: annee
        tests:
          - not_null


  # Agriculture provenant de PostgreSQL.
  - name: stg_postgres_agriculture
    columns:
      - name: fnid
        tests:
          - not_null

      - name: produit
        tests:
          - not_null

      - name: systeme_production
        tests:
          - accepted_values:
              arguments:
                values: ['Pluvial', 'Irrigué', 'Décrue (PS)']
              config:
                severity: warn


  # Agriculture provenant de MongoDB.
  - name: stg_mongo_agriculture
    columns:
      - name: fnid
        tests:
          - not_null

      - name: produit
        tests:
          - not_null

      - name: systeme_production
        tests:
          - accepted_values:
              arguments:
                values: ['Pluvial', 'Irrigué', 'Décrue (PS)']
              config:
                severity: warn


  # Agriculture provenant de Kafka.
  - name: stg_kafka_agriculture
    columns:
      - name: fnid
        tests:
          - not_null

      - name: produit
        tests:
          - not_null

      - name: systeme_production
        tests:
          - accepted_values:
              arguments:
                values: ['Pluvial', 'Irrigué', 'Décrue (PS)']
              config:
                severity: warn